### PR TITLE
v2.x WDT & RTC libraries

### PR DESCRIPTION
**Pull request by adamgarbo**
Hi @Wenn0101 ,

Here is the rewritten WDT library for v2.x of the Apollo3 Core. I based it on the format of the RTC library that @oclyke rewrote for v2.x

I've standardized the RTC and WDT intra-library instantiations, so the objects are now `wdt` and `rtc` (lowercase). This is handy, though I suspect some users may like to have more control over how they create their objects.

I also fixed the low-power examples with some assistance from @paulvha. As UART is handled differently now with Mbed OS, I simply modified the low power code so that it manually disables/reenables the UART0 TX/RX pins. It was also necessary to enable the lower 512K of memory since v2.x code is 10x the size of v1.x (Mbed is a hog).

All examples compile using a SparkFun Redboard Artemis.

Happy to assist further or make any necessary changes.

Cheers,
Adam

### CODE REVIEW

**Comment by jerabaul29** [comment]
Any plans to merge this into main?

**Comment by adamgarbo** [comment]
Hi @jerabaul29,

I suspect this will likely be included with v2.1. However, I believe more testing is required. I recently tested the libraries in a larger project and have been observing some strange behaviour with alarm interrupts failing to trigger, or triggering prematurely, as well as funny RTC/WSR ISR behaviour. 

I'm actively looking into this.

Cheers,
Adam

**Comment by Wenn0101** [comment]
^ Yep. Hoping to include this functionality in v2.1.0.

I will be doing more testing in the coming week.

**Comment by adamgarbo** [comment]
@Wenn0101, after some [good discussions on the forums](https://forum.sparkfun.com/viewtopic.php?p=224309#p224296), I've updated the low power code to the correct way of powering down the memory. Up until now, all previous examples have been doing so incorrectly. It is 100% confirmed *not* to brick your board!

**Review by Wenn0101 — APPROVED** [review]

**Pull request merged**
