### PR TITLE
disable adc channels while reconfiguring

### PR DESCRIPTION
**Pull request by oclyke**
Addresses #131

### CODE REVIEW

**Comment by nseidle** [comment]
I can't get the analog example to work on this PR but master works. I'm testing on ATP with trimpot, A29. What's your test setup?

**Comment by oclyke** [comment]
@paulvha I am also seeing the same results. The addition of ```am_hal_adc_disable``` in the ```ap3_change_channel``` routine appears to prevent the ADC from operating correctly. 

Have you tested the changes that you suggest in #131? If so can you tell from the [diffs](https://github.com/sparkfun/Arduino_Apollo3/pull/135/files) of this PR what the culprit may be?

Without taking more time to dive into this I can't tell what exactly the issue is. Perhaps ADC startup time?

**Comment by paulvha** [comment]
I have tested both and left it in my code work correctly. Let me try to do a pull request and sent an update. I used this on couple of different ADC lines.

**Comment by paulvha** [comment]
Hi Owen,

I have reviewed but it is missing a couple of things. I can not create a pull request to handle, Attached, I hope, the ap3_analog_cpp in the zip. Search on PVH  (in capitals) and you will find the places to change ( 7 lines of info)
[ap3_analog.zip](https://github.com/sparkfun/Arduino_Apollo3/files/4269092/ap3_analog.zip)

regards,
Paul

**Comment by oclyke** [comment]
@paulvha the error in the original PR was that the method used to correctly set the interrupt mask (```am_hal_adc_interrupt_status```) only looked for interrupt flags enabled in the HAL layer. Changing this option to return **any** interrupt flag solved the problem. I'm going to merge these changes now.

Thanks a ton for your contribution!

**Pull request merged**
