### PR TITLE
Add platformio package.json file

### PR DESCRIPTION
**Pull request by nigelb**
See sparkfun/Arduino_Apollo3#14 and nigelb/platform-apollo3blue#8

### CODE REVIEW

**Comment by jerabaul29** [comment]
Could this be added for both core v1 and v2? :) .

**Comment by jerabaul29** [comment]
I.e. to add to core v1 I think it would be necessary to add one pull request to the specific branch: https://github.com/sparkfun/Arduino_Apollo3/tree/v1 :) . We are quite a few users out there who do want bare metal use, so would be extremely helpful to get this for core v1 too :) .

**Comment by nigelb** [comment]
@jerabaul29, It is already in [core v1](https://github.com/sparkfun/Arduino_Apollo3/blob/v1/package.json), its version number just needs to be bumped.

**Review by Wenn0101 — APPROVED** [review]

**Comment by jerabaul29** [comment]
Aaah, ok, so in core v1 this does not work well because this:

https://github.com/sparkfun/Arduino_Apollo3/blob/87a33ce12049ff10c6d0d7e6ab9038e4d874b36e/package.json#L4

should be 1.2.3 instead of 1.0.23, right? :) . @Wenn0101 would it be possible to patch the core v1 branch with the correct version number in the json config file? :) .

**Pull request merged**
