### PR TITLE
Add first wiki pages and update ACKNOWLEDGEMENTS.md

### PR DESCRIPTION
**Pull request by ComputerAided**
Added preliminary home page and software interrupts page to wiki, as a result of issue #34 in sparkfun/Ardunio_Apollo3. Add name to contributors list.

### CODE REVIEW

**Comment by ComputerAided** [comment]
I'm not sure if the wiki pages will transfer over by forking the repository, so let me know if there is a better way to do this.

**Comment by oclyke** [comment]
@ComputerAided I see the trouble here - your wiki changes are not coming through. Check out this article (which I will be following).

https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

I will accept this PR (to get your name on Acknowledgements) and then give you the link to the new Wiki repo for you to repeat this PR. Thanks!

**Comment by oclyke** [comment]
@ComputerAided I've made it possible for users to edit the wiki by editing this repo: https://github.com/sparkfun/Arduino_Apollo3-wiki

Can you repeat your PR here with the Wiki changes? Thanks!

**Comment by ComputerAided** [comment]
@oclyke, it is at sparkfun/Arduino_Apollo3-wiki#1

**Comment by oclyke** [comment]
Ahh! Sorry @ComputerAided I've royally messed up. Please keep a copy of your changes locally for a moment while I sort it out...

**Comment by ComputerAided** [comment]
It's okay @oclyke, just let me know when to create a new pull request.

**Comment by oclyke** [comment]
Alright here you go! (had to make a new repo because I unthinkingly made changes to the private wiki and had no good way to resolve the merge conflicts, so the Travis CI sync method got messed up)

https://github.com/sparkfun/Arduino_Apollo3_wiki

Thanks for the patience!

**Comment by ComputerAided** [comment]
@oclyke I made a new PR, but I think I am getting a merge conflict again. I'll keep the files locally if you need to sort anything out.

**Pull request merged**
