### PR TITLE
Release

### PR DESCRIPTION
**Pull request by Wenn0101**
Bring latest changes into master for release

### CODE REVIEW

**Comment by nseidle** [comment]
This looks really good. I'm testing bits of it now.

Are you intending to use [2017 compiler](https://github.com/sparkfun/Arduino_Apollo3/pull/163/files#diff-d638a47d1ca0e2a5585fb34c7d7fb0f9L66) or 2018? I have to use 2018 to get any Arduino sketch to run properly.

**Comment by oclyke** [comment]
@nseidle intending to use 2018 - should already be in the master branch because I [circumvented the process this morning](https://github.com/sparkfun/Arduino_Apollo3/commit/d6997accf6f4b57908aaa6f46a0200abefe8a725)

**Comment by oclyke** [comment]
I like the way the commit history looks here - mostly names of PRs that will be easy to translate into a changelog! In the future ideally it would be just PR merges in this branch

**Comment by nseidle** [comment]
I just did a ~200 hundred attach/detach interrupts and no crashes. Much improved!

**Comment by stephenf7072** [comment]
I'm not sure if there's a protocol, but given the the time since last core release and the number of changes (inc. the new Ambiq SDK), might I suggest it's time for core v1.1.0 instead of v1.0.31.

This branch is working for me on my custom board (including the new interrupt fixes, which seem to have resolved issue #151 ), I've got it running a simulated logging campaign for 24hrs (and then some), and will report any issues.

**Comment by oclyke** [comment]
@stephenf7072 I am okay with that proposal.

Our principal is to follow the [Semantic Versioning](https://semver.org/) guidelines. However our application of these is a little murky because we are not dictating the Arduino API.

For example when we add a peripheral port - e.g. Serial - is that:
* a) a bug fix (the bug being the previous lack of support for a defined Arduino capability)
* b) a backward-compatible functionality addition (this seems most correct to me if you view the core as a collection of independent chunks of functionality)

I suppose I was just being lazy by incrementing the patch number all the time.

I also think that v1.1.0 is a good signpost marking the dawn of our new more standardized version management practices.

Any thoughts from others? Any reason why I should not merge and create release 1.1.0?

**Comment by stephenf7072** [comment]
Thanks Owen, good to know.  Ran all my logging/interrupts test code overnight and it's still going (where it would have crashed by now), happy days.

**Pull request merged**
